version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: valpas312
      POSTGRES_PASSWORD: valpas312pass
      POSTGRES_DB: nestjsdb
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5432:5432"