services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: valpas312
      POSTGRES_PASSWORD: valpas312pass
      POSTGRES_DB: db
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data